# Generated by Django 5.0.2 on 2025-04-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("game_mode", models.CharField(max_length=32)),
                ("map_name", models.CharField(max_length=64)),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField(blank=True, null=True)),
                ("rounds_played", models.IntegerField(default=0)),
                ("team_ct_score", models.IntegerField(default=0)),
                ("team_t_score", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("phase", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "winning_team",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "win_condition",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="matches.match",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("match", "round_number"), name="unique_round"
            ),
        ),
    ]
