# Generated by Django 5.0.2 on 2025-04-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                ("weapon_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("type", models.CharField(max_length=32)),
                ("max_clip", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatchStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("mvps", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
                (
                    "steam_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.steamaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRoundState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("health", models.IntegerField()),
                ("armor", models.IntegerField()),
                ("money", models.IntegerField()),
                ("equip_value", models.IntegerField()),
                ("round_kills", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
                (
                    "steam_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.steamaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=32)),
                ("ammo_clip", models.IntegerField(blank=True, null=True)),
                ("ammo_reserve", models.IntegerField(blank=True, null=True)),
                ("paintkit", models.CharField(default="default", max_length=64)),
                (
                    "player_round_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="stats.playerroundstate",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stats.weapon"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playermatchstat",
            constraint=models.UniqueConstraint(
                fields=("steam_account", "match"), name="unique_player_match_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerroundstate",
            constraint=models.UniqueConstraint(
                fields=("match", "round_number", "steam_account"),
                name="unique_player_round_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerweapon",
            constraint=models.UniqueConstraint(
                fields=("player_round_state", "weapon"), name="unique_player_weapon"
            ),
        ),
    ]
