# Generated by Django 5.2 on 2025-04-16 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('matches', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerroundstate',
            name='unique_player_round_state',
        ),
        migrations.RemoveConstraint(
            model_name='playerweapon',
            name='unique_player_weapon',
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='state_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerweapon',
            name='state_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='playerroundstate',
            constraint=models.UniqueConstraint(fields=('match', 'round_number', 'steam_account', 'state_timestamp'), name='unique_player_round_state_temporal'),
        ),
        migrations.AddConstraint(
            model_name='playerweapon',
            constraint=models.UniqueConstraint(fields=('player_round_state', 'weapon', 'state_timestamp'), name='unique_player_weapon_temporal'),
        ),
    ]
