# Generated by Django 5.2 on 2025-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_playerroundstate_unique_player_round_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
