# Generated by Django 5.2 on 2025-04-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_steamaccount_user'),
        ('matches', '0001_initial'),
        ('stats', '0006_remove_old_field_add_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundstate',
            name='team',
            field=models.CharField(default='SPEC', max_length=32),
        ),
        migrations.AlterField(
            model_name='playerweapon',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AlterField(
            model_name='playerweapon',
            name='steam_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.steamaccount'),
        ),
    ]
