# Generated by Django 5.2 on 2025-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_steamaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamaccount',
            name='auth_token',
            field=models.CharField(max_length=128),
        ),
    ]
