# Generated by Django 5.2 on 2025-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_steamaccount_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamaccount',
            name='auth_token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
